#!/usr/bin/env bash
# displays a story with each line of /etc/passwd.

input="/etc/passwd"
while IFS=: read -r h1 h2 h3 h4 h5 h6 h7
do
    echo "The user $h1 is part of the $h4 gang, lives in $h6 and rides $h7. $h3's place is protected by the passcode $h2, more info about the user here: $h5"
done < "$input"
